### ISSUE TITLE
Failed to create orbit: Unauthorized while Uploading Credentials To Kepler

### ISSUE THREAD

**Issue by eremef** [spruceid/tzprofiles#104]
I created Basic Profile Information and Twitter Account Verification
![image](https://user-images.githubusercontent.com/34741103/122929981-d5641700-d36b-11eb-9244-b1e34d2b5b16.png)

Then I clicked Deploy Profile
Signed (twice) with Kukai Wallet (tried also with Temple Wallet)
and then I got this error:
Failed to create orbit: Unauthorized

that looks like this:
![image](https://user-images.githubusercontent.com/34741103/122930599-6935e300-d36c-11eb-83f5-cef5e9d9d765.png)

browsers: Brave and Chrome
feature, bug? ;)

**Comment by sbihel** [comment]
Hiya, I believe for your case we just released a temporary fix. Apologies. 

In the case it hasn't been resolved, if you could get a hold on the failing requests in the browser's console that would be grand.

**Comment by obstropolos** [comment]
This has since been resolved - closing the issue here!

**Comment by eremef** [comment]
true story! it works fine now :)
