### ISSUE TITLE
Awaiting Upload forever status

### ISSUE THREAD

**Issue by scifinft** [spruceid/tzprofiles#176]
Ive tried so many times to validate all my information but it always "Awaiting Upload " status... can you please assist me with this issue?

**Comment by obstropolos** [comment]
Hey - please make sure to hit "Deploy Profile" and follow the steps after that to successfully deploy it 👍

**Comment by scifinft** [comment]
> Hey - please make sure to hit "Deploy Profile" and follow the steps after that to successfully deploy it 👍

![image](https://user-images.githubusercontent.com/92907955/147127286-1d1521e4-01e7-426c-aea6-90b849108399.png)
 this is the only I get

**Comment by scifinft** [comment]
thank you "upload claims"!
