### ISSUE TITLE
IRIs for VCs

### ISSUE THREAD

**Issue by clehner** [spruceid/tzprofiles#51]
This application defines some application-specific JSON-LD [terms](https://www.w3.org/TR/json-ld11/#terms) for the Verifiable Credentials being issued:
https://github.com/spruceid/tzprofiles/blob/a0dcb9d/worker/src/lib.rs#L51-L67
https://github.com/spruceid/tzprofiles/blob/a0dcb9d/dapp/src/basic_profile.ts#L19-L25
- BasicProfile
- TwitterVerification
- TwitterVerificationPublicTweet
  - handle
  - timestamp
  - tweetId

It would be helpful for people trying to understand these verifiable credentials to be able to resolve these IRIs as URLs in a web browser to get some specification/documentation of the IRI and its intended meaning. Currently they are resources directly under tzprofiles.com - but they are not served by this web app. Either the web app should serve them or they should be changed to use a different domain name, e.g. `ld.tzprofiles.com`. They could also be namespaced by date and/or topic. They could be consolidated under one or more primary resources (pages) using the [fragment id](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5) to distinguish them (like how [security-vocab](https://w3c-ccg.github.io/security-vocab/) works), or they could be kept as separate primary resources (like how schema.org works).

**Comment by wyc** [comment]
e.g., `ld.tzprofiles.com/verifications/twitter#TwitterVerification`
e.g., `ld.tzprofiles.com/data/profile#BasicProfile`
