### ISSUE TITLE
Rename TZIP-023 -> TZIP-024

### ISSUE THREAD

**Issue by wyc** [spruceid/tzprofiles#58]
As per: https://gitlab.com/tzip/tzip/-/blob/450e59b30ae92deeeb4b4c84bff20e9b05bc8a39/proposals/tzip-24/tzip-24.md

We should further add metadata to smart contract deployment describing the TZIP-024 instance as a `tzprofile` (perhaps under an appropriate TZIP-016 key) so it's easier to query. TZIP-024 may be used for other applications than tzprofiles, so it is important that we define the resolution steps for the tzprofiles explicitly.

Furthermore, the TZIP-024 reference in the `interfaces` metadata value should ideally reflect a hash of the commit containing the TZIP definition.

**Comment by sbihel** [comment]
I'm not quite sure about having TZIP-024 be more generic than just `tzprofile`. In my opinion it's too generic in that it just describes the a contract that exposes a set of three elements, but then it's also really specific to our use-case with the use of a set (I can think of similar use-cases that require an ordered list), a specific hash, and the use of content type (which might not be necessary for some use cases, or also tools will have to support a list of content types which might grow large).

I'm not being very intelligible -- I'm simply on the fence about the non-equivalence between TZIP-024 and `tzprofile`. 

I also don't know what TZIP-016 would be appropriate except maybe `name`.
