### ISSUE TITLE
Support for Web Domain Verification

### ISSUE THREAD

**Issue by obstropolos** [spruceid/tzprofiles#61]
# Clarification and Motivation 
As Tezos Profiles grows, it's important to have a mix of social accounts and publicly available information for a user to associate with their public key. Outside of social accounts, proving web domain ownership is available through a number of methods. 

Additionally, if we wanted to see if a user was the owner of a traditional web domain to not only prove ownership but demonstrate it alongside ownership of a Tezos Domain, they should be able to, and receive a relevant credential that they can demonstrate. 

# Acceptance Criteria
As a user: 
- I can connect my wallet to Tezos Profiles and view available credentials
- I can obtain a Web Domain credential by doing the following:
   - Entering my owned web domain
   - Sign a message using my Tezos wallet 
   - Receive a string to add to a TXT record through my domain registrar
   - Wait for the verification (which might take time - and the service informs me of this)
   - Be able to retry in the case of retrieval failure 
- I can add this web domain credential to my existing smart contract if I've already deployed a profile.

**Comment by wallopthecat** [comment]
Relevant https://crates.io/crates/trust-dns-resolver

**Comment by clehner** [comment]
Related: https://identity.foundation/.well-known/resources/did-configuration/ (uses HTTP well-known and VC rather than TXT record)
