### ISSUE TITLE
Add button to show image to hide potentially NSFW images

### ISSUE THREAD

**Issue by wyc** [spruceid/tzprofiles#89]
Do something similar to what's seen in:

https://tzcomet.io/#/explorer%3Fexplorer-input%3DKT1W4wh1qDc2g22DToaTfnCtALLJ7jHn38Xc

**Comment by obstropolos** [comment]
Adding additional context here - 

As a user: 
- I can view a Tezos profile and reveal someone's `logo` rather than it being displayed from the onset by clicking on it.
- I can see a warning on that logo square notifying me of a potential NSFW image.

**Comment by obstropolos** [comment]
Closing - non-issue due to limited display reach.
